import React from "react";
import { useState } from "react";
import { Link } from "react-router-dom";

const CocktailLetter = () => {
  const [selectedLetter, setSelectedLetter] = useState('');

  const letterSelection = (e) => {
    e.preventDefault();
    setSelectedLetter(e.target.textContent);
    console.log("selectedLetter1", selectedLetter);
  };
  return (
    <div>
      <div className="container">
      <h2 className="title" style={{fontSize: '60px'}}>
          <span>Search By Letter</span> 
      </h2>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        A
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        B
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        C
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        D
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        E
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        F
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        G
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        H
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        I
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        J
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        K
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        L
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        M
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        N
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        O
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        P
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        Q
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        R
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        S
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        T
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        U
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        V
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        W
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        X
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        Y
      </Link>
      <Link
        to={`/CocktailsByLetter/${selectedLetter}`}
        onClick={letterSelection}
      >
        Z
      </Link>
      </div>
    </div>
  );
};

export default CocktailLetter;
